# Generated by Django 5.1.4 on 2024-12-23 01:37

import django.db.models.deletion
import services.models
import services.utils.json_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя категории')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url представление')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дополнено')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ServiceTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя тега')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url представление')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дополнено')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('preview_text', models.TextField(blank=True, max_length=200, verbose_name='Краткое описание(превью)')),
                ('preview_video_url', models.URLField(blank=True, null=True, verbose_name='Видео youtube(превью)')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=services.models.get_upload_to, verbose_name='Преввью картинка')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url представление')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дополнено')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory', verbose_name='Какая категория?')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Блок текста')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Видео youtube')),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.models.get_upload_to, verbose_name='Иллюстрация')),
                ('add', models.JSONField(blank=True, null=True, validators=[services.utils.json_validators.validate_service], verbose_name='JSON поле для рекламы(инфа для запроса)')),
                ('characteristics', models.JSONField(blank=True, null=True, validators=[services.utils.json_validators.validate_characteristics], verbose_name='Таблица')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_section', to='services.service', verbose_name='Какая услуга?')),
            ],
            options={
                'verbose_name': 'Секция услуги',
                'verbose_name_plural': 'Секции услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя подкатегории')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url представление')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дополнено')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory', verbose_name='К какой категории относится?')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicesubcategory', verbose_name='Какая подкатегория?'),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, to='services.servicetags'),
        ),
    ]
