# Generated by Django 5.1.4 on 2024-12-23 01:37

import django.db.models.deletion
import services.utils.json_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя категории')),
                ('slug', models.SlugField(verbose_name='Url предвтавление')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дополнено')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Блок текста')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Видео youtube')),
                ('add', models.JSONField(blank=True, null=True, validators=[services.utils.json_validators.validate_service], verbose_name='JSON поле для рекламы(инфа для запроса)')),
                ('characteristics', models.JSONField(blank=True, null=True, validators=[services.utils.json_validators.validate_characteristics], verbose_name='Таблица характеристик')),
            ],
            options={
                'verbose_name': 'Секция поста блога',
                'verbose_name_plural': 'Секции постов блога',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя тега блога')),
                ('slug', models.SlugField(verbose_name='Url представление')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дополнено')),
            ],
            options={
                'verbose_name': 'Тег блога',
                'verbose_name_plural': 'Теги блога',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_text', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание(превью)')),
                ('preview_video_url', models.URLField(blank=True, null=True, verbose_name='Видео youtube(превью)')),
                ('title', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(verbose_name='Url представление')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дополнено')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Какая категория?')),
            ],
            options={
                'verbose_name': 'Пост блога',
                'verbose_name_plural': 'Посты блога',
                'ordering': ['pk'],
            },
        ),
    ]
