# Generated by Django 5.1.3 on 2024-12-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_section_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='preview_text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
